### ISSUE TITLE
strip unnecessary .0

### ISSUE THREAD

**Issue by jgehrcke** [drakegroup/sigfig#14]
```
>>> sigfig.round(15272063.214, sigfigs=5)
15272000.0
```
In interfaces when trying to save space then the .0 is redundant information and can / should totally be stripped off.

I found https://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python super interesting. There I also found the pointer to numpy.format_float_positional, and I played with that:
```
>>> np.format_float_positional(15272063, 5, trim='-', fractional=False) 
'15272000'
```

**Comment by createyourpersonalaccount** [comment]
@jgehrcke
For what it's worth, you can find my own module that takes care of this here https://github.com/createyourpersonalaccount/sigfig

**Comment by MikeBusuttil** [comment]
This behavior is expected because:
1. the `sigfig` module returns numbers in the same type (`float` in this case) that they were requested.
2. `float`'s always appear with at least 1 decimal at the end in Python.

To get rid of that `.0` you can request `str`ing output either explicitly or implicitly as shown here:
```
>>> sigfig.round(15272063.214, sigfigs=5, type=str) 
'15272000'
>>> sigfig.round('15272063.214', sigfigs=5) 
'15272000'
```
