### ISSUE TITLE
Support: add zeros make number significant?

### ISSUE THREAD

**Issue by firasm** [drakegroup/sigfig#7]
Hello again!

Quick question, I am building a problem bank for students to do various physics problems, and I'm running into an issue when trying to use the `sigfig` library to format numbers.

For example, if I try:

```
import sigfig
sigfig.round(1.0,sigfigs=3)
```

I would expect:

```
1.00
```

but instead I get 1.0 and a warning

```
UserWarning: warning: 3 significant figures requested from number with only 2 significant figures
  warn("warning: %d significant figures requested from number with only %d significant figures" % (given['sigfigs'], len(num.map)))
```

Do you have any suggestions on how I could handle this case? Is that something you'd consider merging into the library if I made a PR?

I've found the lines of code in the file:

```
        if given['sigfigs'] > len(num.map):
            warn("warning: %d significant figures requested from number with only %d significant figures" % (given['sigfigs'], len(num.map)))
```

My suggestion would be to add an option to "zero-pad" or "zero-fill" until the desired number of sig figs is reached.

**Comment by MikeBusuttil** [comment]
hey @firasm ,

this is working as expected but if you'd like to implement a feature to suppress warnings I'd gladly accept that pr.

The reason you're getting `1.0` as output is because of how Python implements/represents floating point numbers.  See the following examples:
```
>>> 1.0000000
1.0
>>> float(1)
1.0
```
if instead you passed the string '1.0' or Decimal('1.0') to sigfig.round() it would display as one might expect:
```
>>> sigfig.round(str(1.0), sigfigs=3)
warn([..])
'1.00'
```
However, if you'd like to add the `warnings` keyword argument, it could accept values True (default), False, and 'once'.  You could import filterwarnings & resetwarnings `from warnings import warn, filterwarnings, resetwarnings` and then implement the following in the parse_argument section:

- warnings = 'once' => filterwarnings(action='once')
- warnings = False (or falsey) => filterwarnings('ignore')
- warnings = True (or not specified) => resetwarnings() 
- warnings = 'anything else' => resetwarnings() then throw a warning lol

for example:
```
>>> sigfig.round('1.0', sigfigs=3, warnings=False)
'1.00'
```

It would also be good to add test cases to test_warning.csv & test_equality.csv for everything but the 'once' case.

**Comment by MikeBusuttil** [comment]
Also, the end of `api.rst` would benefit from a small write-up to highlight the feature in the docs
